# Generated by Django 3.2 on 2021-04-27 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('titulo', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True, max_length=300)),
                ('info_typegame', models.CharField(blank=True, max_length=150)),
                ('info_datelaunch', models.CharField(blank=True, max_length=150)),
                ('info_designers', models.CharField(blank=True, max_length=150)),
                ('info_developers', models.CharField(blank=True, max_length=150)),
                ('info_publish', models.CharField(blank=True, max_length=150)),
                ('info_genero', models.CharField(blank=True, max_length=150)),
                ('req_processador', models.CharField(blank=True, max_length=150)),
                ('req_memoria', models.CharField(blank=True, max_length=150)),
                ('req_memoriavideo', models.CharField(blank=True, max_length=150)),
                ('req_direct', models.CharField(blank=True, max_length=150)),
                ('req_sistema', models.CharField(blank=True, max_length=150)),
                ('req_volumedisco', models.CharField(blank=True, max_length=150)),
                ('button_mega', models.URLField(blank=True, max_length=300)),
                ('button_media', models.URLField(blank=True, max_length=300)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='photos.category')),
            ],
        ),
    ]
