# Generated by Django 3.2 on 2021-07-15 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='button_media',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='button_mega',
        ),
    ]
